name: "Pip Environment Hash"

outputs:
  hash:
    value: ${{ steps.hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - id: hash
      run: echo "hash=${{ hashFiles('finch/*', 'zebra/*', 'scripts/*', 'MANIFEST.in', 'LICENSE', 'pyproject.toml', 'setup.cfg', 'setup.py') }}" >> $GITHUB_OUTPUT
      shell: bash