name: "Conda Environment Hash"

outputs:
  hash:
    value: ${{ steps.hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/pip_hash
      id: pip
    - run: echo "hash=$(echo ${{ steps.pip.outputs.hash }}-${{ hashFiles('conda/**') }} | sha256sum | head -c 40)" >> $GITHUB_OUTPUT
      id: hash
      shell: bash