{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True, recipe_dir="conda") %}
{% set project = pyproject.get('project') %}
{% set version = load_file_regex(load_file='../finch/data/VERSION', regex_pattern=r'^\S*$') %}

package:
  name: {{ project.get('name') }}
  version: {{ version }}

source:
  path: ../

build:
  number: 1
  string: finch
  preserve_egg_dir: True
  run_exports:
    - openmp
    - python =3.10

requirements:
  build:
    - cmake >=3.14
    - python =3.10
    - {{ compiler('cxx') }}
  host:
    - python =3.10
    - pybind11
    - scikit-build
    - openmp
  run:
    - dask >=2022.11.0
    - distributed >=2022.11.0
    - dask-jobqueue
    - xarray >=2022.11.0
    - pyyaml
    - cfgrib
    - tqdm
    - deprecated
    - matplotx
    - expandvars

about:
  home: {{ project.get('urls').get('Homepage') }}
  license_file: ../LICENSE
  summary: {{ project.get('description') }}