{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project') %}

package:
  name: {{ project.get('name') }}
  version: {{ project.get('version') }}

source:
  path: ..

requirements:
  host:
    - python
  run:
    - dask >= 2022.11.0
    - distributed >= 2022.11.0
    - dask-jobqueue
    - xarray >= 2022.11.0

about:
  home: {{ project.get('urls').get('Homepage') }}
  license: {{ project.get('license') }}
  license_file: LICENSE
  summary: {{ project.get('description') }}