name: "Load Conda Environment"

runs:
  using: "composite"
  steps:
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          activate-environment: finch
          use-mamba: true

      # load cache
      - uses: ./.github/actions/conda_hash.yaml
        id: conda_hash
      - uses: actions/cache@v3
        with:
          path: ${{ env.CONDA_PREFIX }}
          key: conda-${{ steps.conda_hash.outputs.hash }}

      # setup conda environment if we need to create a new cache
      - name: Install conda-build and boa
        run: |
          mamba install conda-build boa -c conda-forge
      - name: Build Package
        run: |
          conda mambabuild -c conda-forge conda
      - name: Installing Package
        run: |
          mamba install -c local -c conda-forge finch_mch