name: "Continuous Delivery"

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    uses: ./.github/workflows

  publish_docs:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/cache@v3
        with:
          path: docs/sphinx/build
          key: ${{ needs.ci.outputs.docs_cache }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sphinx/build/
          force_orphan: true