name: "Continuous Integration"

on:
  workflow_call:
    outputs:
      docs_cache:
        description: "The cache key of the cached build of the documentation"
        value: ${{ jobs.build_docs.outputs.cache }}
  pull_request:
    branches:
      - "main"

jobs:
  package_conda:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: ./.github/actions/conda

  package_pip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: ./.github/actions/pip

  build_docs:
    runs-on: ubuntu-latest
    outputs:
      cache: ${{ steps.cacheid.outputs.cacheid }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: ./.github/actions/pip.yaml
      - name: Sphinx build
        run: |
          sphinx-build docs/sphinx/source docs/sphinx/build
      # cache build
      - id: cacheid
        run: echo "cacheid=docs-$(date + '%m%d%H%M%S%N')" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: docs/sphinx/build
          key: ${{ steps.cacheid.outputs.cacheid }}