name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/products.yaml

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sphinx/build/
          force_orphan: true