name: Packaging
on: [push]
jobs:
  conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - name: Install conda-build and boa
        run: |
          mamba install conda-build boa -c conda-forge
      - name: Build Package
        run: |
          conda mambabuild -c conda-forge conda
      - name: Installing Package
        run: |
          mamba install -c ${CONDA_PREFIX}/conda-bld/  -c conda-forge finch_mch
  setuptools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installing CMake
        uses: lukka/get-cmake@latest
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64
      - name: Installing Build Dependencies
        run: |
          pip install scikit-build "pybind11[global]"
      - name: Installing Package
        run: |
          python setup.py install
