name: Build Products
on: 
  workflow_call:
  pull_request:
    branches:
      - 'main'

jobs:
  package:
    uses: ./.github/workflows/packaging.yaml

  documentation:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Sphinx build
        run: |
          sphinx-build docs/sphinx/source docs/sphinx/build
